### ISSUE TITLE
Release Apollo 1.1.0

### ISSUE THREAD

**Issue by mossmann** [greatscottgadgets/apollo#104]
```[tasklist]
### Tasks
- [ ] #81 
- [ ] https://github.com/greatscottgadgets/apollo/issues/102
- [ ] https://github.com/greatscottgadgets/apollo/pull/106
- [ ] https://github.com/greatscottgadgets/apollo/pull/107
```

**Comment by mossmann** [comment]
Minor version will be bumped because of a small addition to the API in #106.
