### ISSUE TITLE
Release Apollo 0.0.6

### ISSUE THREAD

**Issue by antoinevg** [greatscottgadgets/apollo#33]
This is the tracking issue for the next Apollo release.

```[tasklist]
### Tasks not yet associated with an Issue or Pull Request
- [x] Rename master branch to main
```

```[tasklist]
### Issues
- [ ] https://github.com/greatscottgadgets/apollo/issues/35
- [ ] https://github.com/greatscottgadgets/apollo/issues/43
```

```[tasklist]
### Review, merge or close outstanding pull requests
- [ ] https://github.com/greatscottgadgets/apollo/pull/23
- [ ] https://github.com/greatscottgadgets/apollo/pull/22
- [ ] https://github.com/greatscottgadgets/apollo/pull/37
- [ ] https://github.com/greatscottgadgets/apollo/pull/36
- [ ] https://github.com/greatscottgadgets/apollo/pull/47
```

**Comment by antoinevg** [comment]
Merged into #44
