### ISSUE TITLE
Release Apollo 1.0.4

### ISSUE THREAD

**Issue by mossmann** [greatscottgadgets/apollo#44]
```[tasklist]
### Tasks not yet associated with an Issue or Pull Request
- [x] Check if we need Apollo to differentiate between Saturn-V 1.0 and Apollo firmware
- [x] Rename master branch to main
```

```[tasklist]
### Issues
- [ ] #42
- [ ] https://github.com/greatscottgadgets/apollo/issues/38
- [ ] #39
- [ ] https://github.com/greatscottgadgets/apollo/issues/43
- [ ] https://github.com/greatscottgadgets/apollo/issues/52
- [ ] https://github.com/greatscottgadgets/apollo/issues/26
- [ ] https://github.com/greatscottgadgets/apollo/issues/35
```

```[tasklist]
### Review, merge or close outstanding pull requests
- [ ] https://github.com/greatscottgadgets/apollo/pull/32
- [ ] https://github.com/greatscottgadgets/apollo/pull/34
- [ ] https://github.com/greatscottgadgets/apollo/pull/48
- [ ] https://github.com/greatscottgadgets/apollo/pull/22
- [ ] https://github.com/greatscottgadgets/apollo/pull/23
- [ ] https://github.com/greatscottgadgets/apollo/pull/37
- [ ] https://github.com/greatscottgadgets/apollo/pull/36
```
